# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Cross-OS Install (Source)

# CINTENT >> MANUAL_TRIGGER
# on:
#   schedule:
#     - cron: "0 0 * * 1,4"
#   workflow_dispatch:
on: [repository_dispatch, workflow_dispatch]

jobs:
  install-source:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # CINTENT >> REMOVE_MATRIX
        # python-version: ['3.8', '3.10']
        python-version: ['3.10']

        # CINTENT >> UNSUPPORTED_OS
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    # CINTENT >> INSERT_CINTENT
    - uses: JavidDitty/setup-cintent@3638849e94bdb037f0a405375686a8550e6df904
      with:
        nonblocking: true

    - name: Install tox
      run: |
        pip install --upgrade pip
        pip install --upgrade tox tox-gh-actions

    - name: Install hover
      run: |
        tox -e install

    # CINTENT >> INSERT_CINTENT
    - name: Upload CIntent Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.CINTENT_ARTIFACT_NAME }}
        path: ${{ env.CINTENT_LOGS }}
